package promej.putils.pro.putils.utils;

import java.util.HashMap;
import java.util.Map;

public class EnchantReplace {
    public static Map<String, String> enchants = new HashMap<String, String>();
    private static final String GRAY_CUSTOM = "#BEBEBE";
    private static final String BLUE_CUSTOM = "#1A68CD";
    private static final String PURPLE_CUSTOM = "light_purple";

    public static void init() {
        EnchantReplace.addVanila(" Разящий клинок:gray", "sweeping");
        EnchantReplace.addVanila(" Отбрасывание:gray", "knockback");
        EnchantReplace.addVanila(" Острота:gray", "sharpness");
        EnchantReplace.addVanila(" Небесная кара:gray", "smite");
        EnchantReplace.addVanila(" Добыча:gray", "looting");
        EnchantReplace.addVanila(" Заговор огня:gray", "fire_aspect");
        EnchantReplace.addVanila(" Бич членистоногих:gray", "bane_of_arthropods");
        EnchantReplace.addVanila(" Эффективность:gray", "efficiency");
        EnchantReplace.addVanila(" Шёлковое касание:gray", "silk_touch");
        EnchantReplace.addVanila(" Удача:gray", "fortune");
        EnchantReplace.addVanila(" Ударная волна:gray", "punch");
        EnchantReplace.addVanila(" Сила:gray", "power");
        EnchantReplace.addVanila(" Воспламенение:gray", "flame");
        EnchantReplace.addVanila(" Бесконечность:gray", "infinity");
        EnchantReplace.addVanila(" Тягун:gray", "riptide");
        EnchantReplace.addVanila(" Пронзатель:gray", "impaling");
        EnchantReplace.addVanila(" Громовержец:gray", "channeling");
        EnchantReplace.addVanila(" Верность:gray", "loyalty");
        EnchantReplace.addVanila(" Шипы:gray", "thorns");
        EnchantReplace.addVanila(" Прочность:gray", "unbreaking");
        EnchantReplace.addVanila(" Починка:gray", "mending");
        EnchantReplace.addVanila(" Проклятие утраты:gray", "vanishing_curse");
        EnchantReplace.addVanila(" Проклятие несъёмности:gray", "binding_curse");
        EnchantReplace.addVanila(" Приманка:gray", "lure");
        EnchantReplace.addVanila(" Морская удача:gray", "luck_of_the_sea");
        EnchantReplace.addVanila(" Огнеупорность:gray", "fire_protection");
        EnchantReplace.addVanila(" Защита от снарядов:gray", "projectile_protection");
        EnchantReplace.addVanila(" Защита:gray", "protection");
        EnchantReplace.addVanila(" Взрывоустойчивость:gray", "blast_protection");
        EnchantReplace.addVanila(" Подводное дыхание:gray", "respiration");
        EnchantReplace.addVanila(" Подводник:gray", "aqua_affinity");
        EnchantReplace.addVanila(" Ходьба по воде:gray", "frost_walker");
        EnchantReplace.addVanila(" Невесомость:gray", "feather_falling");
        EnchantReplace.addVanila(" Подводная ходьба:gray", "depth_strider");
        enchants.put("arborist", "Арборист:#BEBEBE");
        enchants.put("beheading", "Обезглавливание:#BEBEBE");
        enchants.put("buckshot", "Картечь:#BEBEBE");
        enchants.put("chopless", "Безмолвный:#BEBEBE");
        enchants.put("cleave", "Осколки:#BEBEBE");
        enchants.put("collateral", "Проходимость:#BEBEBE");
        enchants.put("conclude", "Заключение:#BEBEBE");
        enchants.put("cranial", "Черепной:#BEBEBE");
        enchants.put("defender", "Защитник:#BEBEBE");
        enchants.put("deflection", "Отклонение:#BEBEBE");
        enchants.put("disable", "Отключение:#BEBEBE");
        enchants.put("diverse", "Достойный:#BEBEBE");
        enchants.put("dousing", "Обливание:#BEBEBE");
        enchants.put("drill", "Сверление:#BEBEBE");
        enchants.put("dullness", "Ослабление:#BEBEBE");
        enchants.put("dweller", "Аспект защитника:#BEBEBE");
        enchants.put("electroshock", "Электрошок:#BEBEBE");
        enchants.put("endinfusion", "Крушитель Энда:#BEBEBE");
        enchants.put("evasion", "Уклонение:#BEBEBE");
        enchants.put("extinguishing", "Защита от огня:#BEBEBE");
        enchants.put("extract", "Извлекание:#BEBEBE");
        enchants.put("famine", "Голод:#BEBEBE");
        enchants.put("farmhand", "Батрак:#BEBEBE");
        enchants.put("fetching", "Зимний охотник:#BEBEBE");
        enchants.put("flinch", "Страх:#BEBEBE");
        enchants.put("forcefield", "Силовое поле:#BEBEBE");
        enchants.put("freerunner", "Мягкое падение:#BEBEBE");
        enchants.put("fury", "Зовущий:#BEBEBE");
        enchants.put("graceful", "Изящность:#BEBEBE");
        enchants.put("grapple", "Захват:#BEBEBE");
        enchants.put("greenthumb", "Растительность:#BEBEBE");
        enchants.put("grit", "Песчаный:#BEBEBE");
        enchants.put("hellish", "Адский:#BEBEBE");
        enchants.put("hook", "Крюк:#BEBEBE");
        enchants.put("horde", "Орда:#BEBEBE");
        enchants.put("iceshot", "Ледяной выстрел:#BEBEBE");
        enchants.put("identify", "Идентифицирование:#BEBEBE");
        enchants.put("ignite", "Зажигание:#BEBEBE");
        enchants.put("impact", "Влияние:#BEBEBE");
        enchants.put("incandescence", "Поджигание:#BEBEBE");
        enchants.put("infuriate", "Гнев:#BEBEBE");
        enchants.put("insecticide", "Инсектицид:#BEBEBE");
        enchants.put("instantaneous", "Мгновенный:#BEBEBE");
        enchants.put("invigoration", "Бодрость:#BEBEBE");
        enchants.put("kinetic", "Кинетика:#BEBEBE");
        enchants.put("launch", "Запуск:#BEBEBE");
        enchants.put("leeching", "Пиявка:#BEBEBE");
        enchants.put("lesion", "Поражение:#BEBEBE");
        enchants.put("levitate", "Левитация:#BEBEBE");
        enchants.put("liquidshot", "Жидкий выстрел:#BEBEBE");
        enchants.put("luckycatch", "Удачный улов:#BEBEBE");
        enchants.put("magnetic", "Магнитный:#BEBEBE");
        enchants.put("marking", "Маркировка:#BEBEBE");
        enchants.put("marksman", "Стрелок:#BEBEBE");
        enchants.put("backstab", "Удар в спину:#BEBEBE");
        enchants.put("bleed", "Кровотечение:#BEBEBE");
        enchants.put("criticals", "Критичность:#BEBEBE");
        enchants.put("finishing", "Последний удар:#BEBEBE");
        enchants.put("fire_affinity", "Сродство к огню:#BEBEBE");
        enchants.put("first_strike", "Первый удар:#BEBEBE");
        enchants.put("plasmic", "Плазменный:#BEBEBE");
        enchants.put("proximity", "Близость:#BEBEBE");
        enchants.put("razor", "Острое лезвие:light_purple");
        enchants.put("necrotic", "Некротический:#BEBEBE");
        enchants.put("netherinfusion", "Настой Пустоты:#BEBEBE");
        enchants.put("oxygenate", "Кислород:#BEBEBE");
        enchants.put("pacify", "Усмирение:#BEBEBE");
        enchants.put("paladin", "Паладин:#BEBEBE");
        enchants.put("paralyze", "Парализование:#BEBEBE");
        enchants.put("parry", "Парирование:#BEBEBE");
        enchants.put("phantasm", "Фантазм:#BEBEBE");
        enchants.put("plasmic", "Плазменный:#BEBEBE");
        enchants.put("protector", "Покровитель:#BEBEBE");
        enchants.put("proximity", "Близость:#BEBEBE");
        enchants.put("quadrilateralism", "Четырехсторонность:#BEBEBE");
        enchants.put("radiance", "Сияние:#BEBEBE");
        enchants.put("rage", "Ярость:#BEBEBE");
        enchants.put("reaper", "Жнец:#BEBEBE");
        enchants.put("reel", "Притягивание:#BEBEBE");
        enchants.put("reinforcement", "Армирование:#BEBEBE");
        enchants.put("rejuvenation", "Регенерация:#BEBEBE");
        enchants.put("respirator", "Респиратор:#BEBEBE");
        enchants.put("revenant", "Выживший:#BEBEBE");
        enchants.put("sating", "Насыщение:#BEBEBE");
        enchants.put("serrated", "Зубчатость:#BEBEBE");
        enchants.put("settle", "Пронзание криперов:#BEBEBE");
        enchants.put("shockwave", "Ударная волна:#BEBEBE");
        enchants.put("shotassist", "Броня лучника:#BEBEBE");
        enchants.put("sickening", "Тошнотворность:#BEBEBE");
        enchants.put("slicing", "Нарезка:#BEBEBE");
        enchants.put("spearfishing", "Подводная охота:#BEBEBE");
        enchants.put("spiked", "Шипастый:#BEBEBE");
        enchants.put("stab", "Трезубоносец:#BEBEBE");
        enchants.put("stalwart", "Стойкость:#BEBEBE");
        enchants.put("stoneswitcher", "Каменный переключатель:#BEBEBE");
        enchants.put("strayaaspect", "Замедление:#BEBEBE");
        enchants.put("succession", "Непрерывный ряд:#BEBEBE");
        enchants.put("sycophant", "Сикофант:#BEBEBE");
        enchants.put("tectonic", "Тектоника:#BEBEBE");
        enchants.put("tornado", "Торнадо:#BEBEBE");
        enchants.put("transfuse", "Переработка:#BEBEBE");
        enchants.put("vampireaspect", "Вампирский аспект:#BEBEBE");
        enchants.put("voidaffinity", "Пустота:#BEBEBE");
        enchants.put("voltage", "Напряжение:#BEBEBE");
        enchants.put("wateraffinity", "Близость к воде:#BEBEBE");
        enchants.put("wateraspect", "Водный аспект:#BEBEBE");
        enchants.put("weakening", "Ослабление:#BEBEBE");
        enchants.put("woodswitcher", "Искусный лесоруб:#BEBEBE");
        enchants.put("wisdom", "Мудрость:#BEBEBE");
        enchants.put("intellect", "Интеллект:light_purple");
        enchants.put("supercrtitical", "Сверхкритический:#BEBEBE");
        enchants.put("infernal_touch", "Адское прикосновение:#BEBEBE");
        enchants.put("aiming", "Прицеливание:light_purple");
        enchants.put("cerebral", "Церебральный:#BEBEBE");
        enchants.put("optics", "Оптика:#BEBEBE");
        enchants.put("rapid", "Стремительный:#BEBEBE");
        enchants.put("arcanic", "Арканический:#BEBEBE");
        enchants.put("frozen", "Заморозка:#BEBEBE");
        enchants.put("spring", "Попрыгун:light_purple");
        enchants.put("blast_mining", "Взрывная добыча:#BEBEBE");
        enchants.put("dynamite", "Динамит:#1A68CD");
        enchants.put("energizing", "Энергетика:light_purple");
        enchants.put("introversion", "Интроверсия:#BEBEBE");
        enchants.put("thor", "Тор:#BEBEBE");
        enchants.put("supercritical", "Сверхкритический:#BEBEBE");
        enchants.put("goliath", "Голиаф:#BEBEBE");
        enchants.put("soulbound", "Связанный душой:light_purple");
        enchants.put("diurnal", "Дневной:#BEBEBE");
        enchants.put("quick_charge", "Быстрая зарядка:#BEBEBE");
        enchants.put("preservation", "Сохранение:light_purple");
        enchants.put("prosperity", "Высшее Процветание:light_purple");
        enchants.put("thrive", "Процветание:#BEBEBE");
        enchants.put("stamina", "Выносливость:#BEBEBE");
        enchants.put("escape", "Побег:#BEBEBE");
        enchants.put("rebounding", "Отскок:#BEBEBE");
        enchants.put("disappear", "Исчезание:#BEBEBE");
        enchants.put("shot_assist", "Броня лучника:#BEBEBE");
        enchants.put("carve", "Вырезание:light_purple");
        enchants.put("streamlining", "Оптимизация:light_purple");
        enchants.put("soul_speed", "Скорость Души:#BEBEBE");
        enchants.put("abrasion", "Истирание:#BEBEBE");
        enchants.put("daxterous", "Ловкость:#BEBEBE");
        enchants.put("vitalize", "Оживление:#1A68CD");
        enchants.put("lumberjack", "Лесоруб:#BEBEBE");
        enchants.put("missile", "Смертоносец:#1A68CD");
        enchants.put("repairing", "Ремонт:light_purple");
        enchants.put("life_steal", "Кража жизни:light_purple");
        enchants.put("cubism", "Кубический:#BEBEBE");
        enchants.put("end_infusion", "Крушитель Энда:#BEBEBE");
        enchants.put("stray_aspect", "Замедление:#BEBEBE");
        enchants.put("toxic", "Токсичность:#BEBEBE");
        enchants.put("annihilate", "Усиленное откидывание:light_purple");
    }

    public static String getString(String id) {
        return enchants.get(id);
    }

    public static void addVanila(String val, String key) {
        enchants.put(key, val);
    }
}

